### ISSUE TITLE
Support Windows MSVC target

### ISSUE THREAD

**Issue by wyhaya** [crossdb-org/crossdb-rust#7]
> https://github.com/crossdb-org/crossdb?tab=readme-ov-file#windows

On the Windows platform, currently only the `x86_64-pc-windows-gnu` target is supported, as compiling crossdb requires MINGW64 and GCC.

@jcwangxp

**Comment by jcwangxp** [comment]
Windows platform APIs libs and MSVC compilers are different from gcc and glibc too much. And there're many lower level controls which is missed in MVSC compiler, ex. the atomic operations.
I plan to support MINGW64 and clang(less work than MSVC) on Windows but not MSVC, MINGW64 is smaller and is preferred for windows.
